


RAW_FOLDER : "fastq08"
BWA_GENOM_REF: "/DATAS/references/hg19/hg19.fa" 
DB_SNP : "/DATAS/references/hg19/annotations/dbSNP_144.b37.vcf.gz"
DB_NSFP : "/DATAS/references/hg19/annotations/dbNSFP2.9.txt.gz"
DB_CLINVAR : "/DATAS/references/hg19/annotations/clinvar.vcf.gz "

SNPEFF_CONFIG: "/APPS/share/snpEff/snpEff.config"

LANES_NUMBER: 4

TARGET_BED_FILE: "DI_panel.bed"
TARGET_BED_SLOP : 10
VCF_QUAL: 20
PEDIGREE_FILE: pedigree.ped

SAMPLES : 
- CGH1040-CI
- CGH1206-P
- CGH1207-M
- CGH150474-P
- CGH150475-M
- CGH150476-CI
- CGH161122-CI
- CGH161123-M
- CGH161124-P
- CGH169-CI
- CGH235-P
- CGH236-M
- CGH539-P
- CGH540-M
- CGH542-CI
- Coriell
- Undetermined



# OUTPUT:
#     - Coriellsmall.varscan.snp.vcf.gz

  # - CGH1008.varscan.snp.vcf
  # - CGH1075.varscan.snp.vcf
  # - CGH1076.varscan.snp.vcf
  # - CGH1077.varscan.snp.vcf
  # - CGH1678.varscan.snp.vcf
  # - CGH1679.varscan.snp.vcf
  # - CGH169.varscan.snp.vcf
  # - Coriell.varscan.snp.vcf
  # - CGH1008.varscan.indel.vcf
  # - CGH1075.varscan.indel.vcf
  # - CGH1076.varscan.indel.vcf
  # - CGH1077.varscan.indel.vcf
  # - CGH1678.varscan.indel.vcf
  # - CGH1679.varscan.indel.vcf
  # - CGH169.varscan.indel.vcf

