


RAW_FOLDER : "fastq08"
BWA_GENOM_REF: "/DATAS/references/hg19/hg19.fa" 
DB_SNP : "/DATAS/references/hg19/annotations/dbSNP_144.b37.vcf.gz"
DB_NSFP : "/DATAS/references/hg19/annotations/dbNSFP2.9.txt.gz"
DB_CLINVAR : "/DATAS/references/hg19/annotations/clinvar.vcf.gz "

SNPEFF_CONFIG: "/APPS/share/snpEff/snpEff.config"

LANES_NUMBER: 4

TARGET_BED_FILE: "DI_panel.bed"
TARGET_BED_SLOP : 10
VCF_QUAL: 20
PEDIGREE_FILE: pedigree.ped

SAMPLES : 
- ASG145494
- BE1
- BE2
- CGH150212-I
- CGH160373-I
- CGH160585-I
- CGH160592-I
- CGH160665-I
- CGH160667-I
- CGH160832-I
- CGH160900-I
- CGH161156-I
- CGH170151-I
- CGH170387-I
- CGH410-I
- Pool-maman-1
- Pool-maman-2
- Pool-papa-1
- Pool-papa-2
- SGT152803-1
- SGT152803-2
- SGT152899
- SGT153103-1
- SGT153103-2


OUTPUT:
    - Coriellsmall.varscan.snp.vcf.gz

  # - CGH1008.varscan.snp.vcf
  # - CGH1075.varscan.snp.vcf
  # - CGH1076.varscan.snp.vcf
  # - CGH1077.varscan.snp.vcf
  # - CGH1678.varscan.snp.vcf
  # - CGH1679.varscan.snp.vcf
  # - CGH169.varscan.snp.vcf
  # - Coriell.varscan.snp.vcf
  # - CGH1008.varscan.indel.vcf
  # - CGH1075.varscan.indel.vcf
  # - CGH1076.varscan.indel.vcf
  # - CGH1077.varscan.indel.vcf
  # - CGH1678.varscan.indel.vcf
  # - CGH1679.varscan.indel.vcf
  # - CGH169.varscan.indel.vcf

